### ISSUE TITLE
accidental unicode input case handling

### ISSUE THREAD

**Issue by bsandeepan95** [bids-standard/pyedf#11]
Okay, I ran a bit of code for testing the error handling block in Python 2.7 and I feel the block is necessary. Run the following example - 

```python
# -*- coding: utf-8 -*-
enc = 'ascii'
x = 'µ Õ ß'

print x

try:
    y = x.encode(enc)
except Exception as e:
    print("Error Message: " + str(e))
    print("Error Type: " + str(type(e)))
    y = 'fail'

print y
print (x == y)
 ```

The output will be like the following - 
```python
Python 2.7.16 (default, Jul 13 2019, 16:01:51)
[GCC 8.3.0] on linux2

µ Õ ß
Error Message: 'ascii' codec can't decode byte 0xc2 in position 0: ordinal not in range(128)
Error Type: <type 'exceptions.UnicodeDecodeError'>
fail
False
```

So errors will occur if there are non-ascii characters, and the code will fail. Now the question is if it is better to let the code fail, or if we should handle the error gracefully and display it to the console for the developer. Let me know your opinion about this @palday .

_Originally posted by @bsandeepan95 in https://github.com/bids-standard/pyedf/pull/10_

**Comment by bsandeepan95** [comment]
To clarify my point:

I am concerned about users using this library to write EDF files, and some inputs are encoded in non-ascii. Since there will be conversion errors thrown during such conditions, then -

1. Is it better to let the module throw error and stop the program?
2. Handle the error gracefully and notify the user in terminal?

Personally, I prefer option one. To me, that is preferred as I can handle the input encoding in dev stage to ensure the `writebyte()` function receives **ascii encoding friendly'** string inputs.

**Comment by robertoostenveld** [comment]
Throwing an error is also informative to the user, who then has to solve the problem her/himself. Hence I think 1 is fine.
