### ISSUE TITLE
rename from pyEDF to pyedf

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/pyedf#5]
We discussed in relation to BIDS-EEG that pybv and pyEDF now have inconsistent capitalization, which is not so nice. 

@sappelhoff commented that all lowercase is the recommended way in PEP8, see: https://www.python.org/dev/peps/pep-0008/#package-and-module-names.

I transferred ownership of this repo from my account to bids-standard and now I am not admin any more. Hence I cannot change the name. Could you please rename it?

thanks

**Comment by chrisfilo** [comment]
I renamed the repo and made you an admin.

**Comment by palday** [comment]
The reserved name is already correct on PyPI. I'll make sure it matches when I add the `setup` script.
