### ISSUE TITLE
Converting from MNE?

### ISSUE THREAD

**Issue by bdyetton** [bids-standard/pyedf#6]
Hi @robertoostenveld,
Just wondering if you have any custom code snippets for saving an mne.io.RawArray to edf using this lib?
Thanks!

**Comment by palday** [comment]
Not directly, but you can use the `Raw.get_data()` method to extract the array and then use this to save it.

**Comment by bdyetton** [comment]
Thanks. I did try this, but found it too slow, so i moved to pyedflib instead.
